<?php

$rankset_names[] = 'Mario';

$rankset_data['Mario'] = [
	['p' => 0, 'str' => 'Non-poster'],
	['p' => 1, 'str' => 'Newcomer'],
	['p' => 10, 'str' => '<img src="img/ranks/microgoomba.gif"><br>Micro-Goomba'],
	['p' => 20, 'str' => '<img src=img/ranks/goomba.gif><br>Goomba'],
	['p' => 35, 'str' => '<img src=img/ranks/redgoomba.gif><br>Red Goomba'],
	['p' => 50, 'str' => '<img src=img/ranks/redparagoomba.gif><br>Red Paragoomba'],
	['p' => 65, 'str' => '<img src=img/ranks/paragoomba.gif><br>Paragoomba'],
	['p' => 80, 'str' => '<img src=img/ranks/shyguy.gif><br>Shyguy'],
	['p' => 100, 'str' => '<img src=img/ranks/koopa.gif><br>Koopa'],
	['p' => 120, 'str' => '<img src=img/ranks/redkoopa.gif><br>Red Koopa'],
	['p' => 140, 'str' => '<img src=img/ranks/paratroopa.gif><br>Paratroopa'],
	['p' => 160, 'str' => '<img src=img/ranks/redparatroopa.gif><br>Red Paratroopa'],
	['p' => 180, 'str' => '<img src=img/ranks/cheepcheep.gif><br>Cheep-cheep'],
	['p' => 200, 'str' => '<img src=img/ranks/redcheepcheep.gif><br>Red Cheep-cheep'],
	['p' => 225, 'str' => '<img src=img/ranks/ninji.gif><br>Ninji'],
	['p' => 250, 'str' => '<img src=img/ranks/flurry.gif><br>Flurry'],
	['p' => 275, 'str' => '<img src=img/ranks/snifit.gif><br>Snifit'],
	['p' => 300, 'str' => '<img src=img/ranks/porcupo.gif><br>Porcupo'],
	['p' => 325, 'str' => '<img src=img/ranks/panser.gif><br>Panser'],
	['p' => 350, 'str' => '<img src=img/ranks/mole.gif><br>Mole'],
	['p' => 375, 'str' => '<img src=img/ranks/beetle.gif><br>Buzzy Beetle'],
	['p' => 400, 'str' => '<img src=img/ranks/nipperplant.gif><br>Nipper Plant'],
	['p' => 425, 'str' => '<img src=img/ranks/bloober.gif><br>Bloober'],
	['p' => 450, 'str' => '<img src=img/ranks/busterbeetle.gif><br>Buster Beetle'],
	['p' => 475, 'str' => '<img src=img/ranks/beezo.gif><br>Beezo'],
	['p' => 500, 'str' => '<img src=img/ranks/bulletbill.gif><br>Bullet Bill'],
	['p' => 525, 'str' => '<img src=img/ranks/rex.gif><br>Rex'],
	['p' => 550, 'str' => '<img src=img/ranks/lakitu.gif><br>Lakitu'],
	['p' => 575, 'str' => '<img src=img/ranks/spiny.gif><br>Spiny'],
	['p' => 600, 'str' => '<img src=img/ranks/bobomb.gif><br>Bob-Omb'],
	['p' => 625, 'str' => '<img src=img/ranks/drybones.gif><br>Dry Bones'],
	['p' => 650, 'str' => '<img src=img/ranks/cobrat.gif><br>Cobrat'],
	['p' => 675, 'str' => '<img src=img/ranks/pokey.gif><br>Pokey'],
	['p' => 700, 'str' => '<img src=img/ranks/spike.gif><br>Spike'],
	['p' => 725, 'str' => '<img src=img/ranks/hedgehog.gif><br>Melon Bug'],
	['p' => 750, 'str' => '<img src=img/ranks/lanternghost.gif><br>Lantern Ghost'],
	['p' => 775, 'str' => '<img src=img/ranks/fuzzy.gif><br>Fuzzy'],
	['p' => 800, 'str' => '<img src=img/ranks/bandit.gif><br>Bandit'],
	['p' => 830, 'str' => '<img src=img/ranks/superkoopa.gif><br>Super Koopa'],
	['p' => 860, 'str' => '<img src=img/ranks/redsuperkoopa.gif><br>Red Super Koopa'],
	['p' => 900, 'str' => '<img src=img/ranks/boo.gif><br>Boo'],
	['p' => 925, 'str' => '<img src=img/ranks/boo2.gif><br>Boo'],
	['p' => 950, 'str' => '<img src=img/ranks/fuzzball.gif><br>Fuzz Ball'],
	['p' => 1000, 'str' => '<img src=img/ranks/boomerangbrother.gif><br>Boomerang Brother'],
	['p' => 1050, 'str' => '<img src=img/ranks/hammerbrother.gif><br>Hammer Brother'],
	['p' => 1100, 'str' => '<img src=img/ranks/firebrother.gif><br>Fire Brother'],
	['p' => 1150, 'str' => '<img src=img/ranks/firesnake.gif><br>Fire Snake'],
	['p' => 1200, 'str' => '<img src=img/ranks/giantgoomba.gif><br>Giant Goomba'],
	['p' => 1250, 'str' => '<img src=img/ranks/giantkoopa.gif><br>Giant Koopa'],
	['p' => 1300, 'str' => '<img src=img/ranks/giantredkoopa.gif><br>Giant Red Koopa'],
	['p' => 1350, 'str' => '<img src=img/ranks/giantparatroopa.gif><br>Giant Paratroopa'],
	['p' => 1400, 'str' => '<img src=img/ranks/giantredparatroopa.gif><br>Giant Red Paratroopa'],
	['p' => 1450, 'str' => '<img src=img/ranks/chuck.gif><br>Chuck'],
	['p' => 1500, 'str' => '<img src=img/ranks/thwomp.gif><br>Thwomp'],
	['p' => 1550, 'str' => '<img src=img/ranks/bigcheepcheep.gif><br>Boss Bass'],
	['p' => 1600, 'str' => '<img src=img/ranks/volcanolotus.gif><br>Volcano Lotus'],
	['p' => 1650, 'str' => '<img src=img/ranks/lavalotus.gif><br>Lava Lotus'],
	['p' => 1700, 'str' => '<img src=img/ranks/ptooie2.gif><br>Ptooie'],
	['p' => 1800, 'str' => '<img src=img/ranks/sledgebrother.gif><br>Sledge Brother'],
	['p' => 1900, 'str' => '<img src=img/ranks/boomboom.gif><br>Boomboom'],
	['p' => 2000, 'str' => '<img src=img/ranks/birdopink.gif><br>Birdo'],
	['p' => 2100, 'str' => '<img src=img/ranks/birdored.gif><br>Red Birdo'],
	['p' => 2200, 'str' => '<img src=img/ranks/birdogreen.gif><br>Green Birdo'],
	['p' => 2300, 'str' => '<img src=img/ranks/iggy.gif><br>Larry Koopa'],
	['p' => 2400, 'str' => '<img src=img/ranks/morton.gif><br>Morton Koopa'],
	['p' => 2500, 'str' => '<img src=img/ranks/wendy.gif><br>Wendy Koopa'],
	['p' => 2600, 'str' => '<img src=img/ranks/larry.gif><br>Iggy Koopa'],
	['p' => 2700, 'str' => '<img src=img/ranks/roy.gif><br>Roy Koopa'],
	['p' => 2800, 'str' => '<img src=img/ranks/lemmy.gif><br>Lemmy Koopa'],
	['p' => 2900, 'str' => '<img src=img/ranks/ludwig.gif><br>Ludwig Von Koopa'],
	['p' => 3000, 'str' => '<img src=img/ranks/triclyde.gif><br>Triclyde'],
	['p' => 3100, 'str' => '<img src=img/ranks/kamek.gif><br>Magikoopa'],
	['p' => 3200, 'str' => '<img src=img/ranks/wart.gif><br>Wart'],
	['p' => 3300, 'str' => '<img src=img/ranks/babybowser.gif><br>Baby Bowser'],
	['p' => 3400, 'str' => '<img src=img/ranks/bowser.gif><br>King Bowser Koopa'],
	['p' => 3500, 'str' => '<img src=img/ranks/yoshi.gif><br>Yoshi'],
	['p' => 3600, 'str' => '<img src=img/ranks/yoshiyellow.gif><br>Yellow Yoshi'],
	['p' => 3700, 'str' => '<img src=img/ranks/yoshiblue.gif><br>Blue Yoshi'],
	['p' => 3800, 'str' => '<img src=img/ranks/yoshired.gif><br>Red Yoshi'],
	['p' => 3900, 'str' => '<img src=img/ranks/kingyoshi.gif><br>King Yoshi'],
	['p' => 4000, 'str' => '<img src=img/ranks/babymario.gif><br>Baby Mario'],
	['p' => 4100, 'str' => '<img src=img/ranks/luigismall.gif><br>Luigi'],
	['p' => 4200, 'str' => '<img src=img/ranks/mariosmall.gif><br>Mario'],
	['p' => 4300, 'str' => '<img src=img/ranks/luigibig.gif><br>Super Luigi'],
	['p' => 4400, 'str' => '<img src=img/ranks/mariobig.gif><br>Super Mario'],
	['p' => 4500, 'str' => '<img src=img/ranks/luigifire.gif><br>Fire Luigi'],
	['p' => 4600, 'str' => '<img src=img/ranks/mariofire.gif><br>Fire Mario'],
	['p' => 4700, 'str' => '<img src=img/ranks/luigicape.gif><br>Cape Luigi'],
	['p' => 4800, 'str' => '<img src=img/ranks/mariocape.gif><br>Cape Mario'],
	['p' => 4900, 'str' => '<img src=img/ranks/luigistar.gif><br>Star Luigi'],
	['p' => 5000, 'str' => '<img src=img/ranks/mariostar.gif><br>Star Mario']
];